### ISSUE TITLE
plugin Not Found while creating network with IPAM & Driver 

### ISSUE THREAD

**Issue by dipak-pawar** [fabric8io/docker-client#93]
While creating network with following option getting `plugin not found` error.

```yml
networks:
  app_net:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "true"
    ipam:
      driver: default
      config:
      - subnet: 172.16.238.0/24
        gateway: 172.16.238.1
      - subnet: 2001:3984:3989::/64
        gateway: 2001:3984:3989::1
```
We don't have `driver_opts` in v[ 1.21](https://github.com/moby/moby/blob/master/docs/api/v1.21.md#connect-a-container-to-a-network).

but I tried it without `driver_opts` as well, getting the same error.
